    --
    -- QC-AdvancedMedic
    --
    cotton_band                         = {name = 'cotton_band', label = 'Cotton Bandage', weight = 0, type = 'item', image = 'cotton_band.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A medical bandage for treating wounds' },
    cloth_band                          = {name = 'cloth_band', label = 'Cloth Strip', weight = 0, type = 'item', image = 'cloth_strip.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A medical bandage for treating wounds'},
    linen_band                          = {name = 'linen_band', label = 'Linen Wrap', weight = 0, type = 'item', image = 'linen_wrap.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A medical bandage for treating wounds' },
    sterile_band                        = {name = 'sterile_band', label = 'Sterilized Gauze', weight = 0, type = 'item', image = 'steril_gauze.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A medical bandage for treating wounds' },
    -- TOURNIQUET TYPES - Wild West 1899 Emergency Control
    tourniquet_rope                     = {name = 'tourniquet_rope', label = 'Rope Tourniquet', weight = 100, type = 'item', image = 'rope_tourniquet.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Emergency rope tourniquet for controlling severe bleeding' },
    tourniquet_leather                  = {name = 'tourniquet_leather', label = 'Leather Tourniquet', weight = 100, type = 'item', image = 'leather_tourniquet.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Emergency leather tourniquet for controlling severe bleeding' },
    tourniquet_cloth                    = {name = 'tourniquet_cloth', label = 'Cloth Tourniquet', weight = 100, type = 'item', image = 'cloth_tourniquet.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Emergency cloth tourniquet for controlling severe bleeding' },
    tourniquet_medical                  = {name = 'tourniquet_medical', label = 'Medical Tourniquet', weight = 100, type = 'item', image = 'medical_tourniquet.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Emergency medical tourniquet for controlling severe bleeding' },
    -- MEDICINE TYPES - Wild West 1899 Pharmaceutical Treatment
    medicine_laudanum                   = {name = 'medicine_laudanum', label = 'Medicine Laudanum', weight = 100, type = 'item', image = 'medicine_laudanum.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Opium-based painkiller - powerful but addictive' },
    medicine_morphine                   = {name = 'medicine_morphine', label = 'Medicine Morphine', weight = 100, type = 'item', image = 'medicine_morphine.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Powerful opiate analgesic - strongest painkiller available' },
    medicine_whiskey                    = {name = 'medicine_whiskey', label = 'Medicine Whiskey', weight = 100, type = 'item', image = 'medicine_whiskey.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Alcohol-based antiseptic and anesthetic - frontier medicine' },
    medicine_quinine                    = {name = 'medicine_quinine', label = 'Medicine Quinine', weight = 100, type = 'item', image = 'medicine_quinine.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Antimalarial and fever reducer - specialized treatment' },
    -- INJECTION TYPES - Wild West 1899 Experimental Medical Injections
    injection_adrenaline                = {name = 'injection_adrenaline', label = 'Rope Tourniquet', weight = 100, type = 'item', image = 'rope_tourniquet.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Cardiac stimulant for emergency resuscitation - use with extreme caution' },
    injection_cocaine                   = {name = 'injection_cocaine', label = 'Rope Tourniquet', weight = 100, type = 'item', image = 'rope_tourniquet.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Local anesthetic for surgical procedures - numbs pain effectively' },
    injection_strychnine                = {name = 'injection_strychnine', label = 'Rope Tourniquet', weight = 100, type = 'item', image = 'rope_tourniquet.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Stimulant for paralysis and respiratory failure - extremely dangerous' },
    injection_saline                    = {name = 'injection_saline', label = 'Rope Tourniquet', weight = 100, type = 'item', image = 'rope_tourniquet.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Hydration and blood volume replacement - safe basic treatment' },
    -- DOCTOR BAG TOOLS - Wild West 1899 Diagnostic & Emergency Tools (v0.2.9+)
    smelling_salts                      = {name = 'smelling_salts', label = 'Smelling Salts', weight = 50, type = 'item', image = 'smelling_salts.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Ammonia compound for reviving unconscious patients' },
    stethoscope                         = {name = 'stethoscope', label = 'Stethoscope', weight = 150, type = 'item', image = 'stethoscope.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Medical instrument for listening to heart and lung sounds' },
    thermometer                         = {name = 'thermometer', label = 'Thermometer', weight = 75, type = 'item', image = 'thermometer.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Mercury thermometer for measuring body temperature' },
    field_surgery_kit                   = {name = 'field_surgery_kit', label = 'Field Surgery Kit', weight = 500, type = 'item', image = 'field_surgery_kit.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Emergency surgical tools for critical field operations' },
